In [1]:
import numpy as np

scores = np.array([
    [45, 67, 89, 34, 56],
    [23, 45, 67, 89, 90],
    [78, 56, 90, 67, 88],
    [34, 45, 23, 56, 78],
    [90, 87, 92, 88, 95],
    [56, 45, 67, 78, 89],
    [12, 23, 34, 45, 56],
    [67, 78, 89, 90, 91],
    [45, 56, 67, 78, 89],
    [88, 77, 66, 55, 44]
])
print(scores)

[[45 67 89 34 56]
 [23 45 67 89 90]
 [78 56 90 67 88]
 [34 45 23 56 78]
 [90 87 92 88 95]
 [56 45 67 78 89]
 [12 23 34 45 56]
 [67 78 89 90 91]
 [45 56 67 78 89]
 [88 77 66 55 44]]


In [3]:
# 1. Find total runs scored by each player
player1=sum(scores[0,:])
print("player 1 :",player1)
player2=np.sum(scores[1,:])
print("player 2 :",player2)
all_player_total=np.sum(scores,axis=1)
print("all players total : ",all_player_total)

player 1 : 291
player 2 : 314
all players total :  [291 314 379 236 452 335 170 415 335 330]


In [29]:
# average_runs of each player
avg_run=np.mean(scores,axis=1)
print("Average runs of each player : ",avg_run)

Average runs of each player :  [58.2 62.8 75.8 47.2 90.4 67.  34.  83.  67.  66. ]


In [31]:
# max and min score of all players
high_score=np.max(scores,axis=1)
print("maximum scores of players:",high_score)

law_score=np.min(scores,axis=1)
print("minimum scores of players",law_score)

maximum scores of players: [89 90 90 78 95 89 56 91 89 88]
minimum scores of players [34 23 56 23 87 45 12 67 45 44]


In [33]:
# in all of the matches print one-one player's maximum and minimum runs only
highest_score = np.max(scores)
print("Highest Score:", highest_score)

lowest_score = np.min(scores)
print("Lowest Score:", lowest_score)

Highest Score: 95
Lowest Score: 12


In [38]:
# print each player runs where avg>70
av_run=np.mean(scores,axis=1)
print(av_run)
runs=np.where(av_run>70)
print(runs)

[58.2 62.8 75.8 47.2 90.4 67.  34.  83.  67.  66. ]
(array([2, 4, 7]),)


In [39]:
# total score of each match
match_total = np.sum(scores, axis=0)

print(match_total)

[538 579 684 680 776]


In [5]:
row_vector = np.array([10,20,30])
col_matr   = np.array([[1,2,3],[4,5,6]])

ans = row_vector + col_matr
print(ans)

[[11 22 33]
 [14 25 36]]


In [8]:
mat1 = np.arange(1,13).reshape(3,4)
mat2 = np.arange(1,13).reshape(4,3)

ans = mat1 + mat2
print(ans)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [13]:
vector = np.array([10,47,52,86,90,10,25,5,38,70])
print(np.max(vector))
print(np.min(vector))
print(np.argmax(vector))
print(np.argmin(vector))
print(np.argsort(vector))

90
5
4
7
[7 0 5 6 8 1 2 9 3 4]


In [4]:
var = np.array([10,20,50,40,60])
var2= np.array([[39,49,59,7,5],[10,20,50,40,60]])
add= var + var2
print(add)

[[ 49  69 109  47  65]
 [ 20  40 100  80 120]]


In [5]:
vector = np.array([5,7,4,6])
print(vector)

[5 7 4 6]


In [21]:
result1 = np.append(arr=vector,values=[[1,2,3,4]])
print(result1)

[5 7 4 6 1 2 3 4]


In [27]:
matrix = np.append([[1,2,3],[4,5,6]],[[7,8,9]],axis=0)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
result2 = np.insert(vector,1,28)
print(result2)

[ 5 28  7  4  6]


In [34]:
array2 = np.arange(1,7).reshape(2,3)
print(array2)

[[1 2 3]
 [4 5 6]]


In [32]:
result = array2.flatten()
print(result)

[1 2 3 4 5 6]
